name: Build and Deploy React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Change directory and Install dependencies
      run: |
        cd xfid-react
        npm install

    - name: Build React application
      run: |
        cd xfid-react
        npm run build

    - name: Deploy to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_XFID_87CBB }}'
        channelId: live  # Remove this line if you don't want to deploy to a specific channel
        projectId: xfid-87cbb
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
